### PR TITLE
versal: authenc: fix PLM DMA timeout

### PR DESCRIPTION
**Pull request by ldts**
Buffer sizes need to be 16 byte aligned or we risk hitting the PLM
AES DMA engine timeout (5 minutes).

This was observed excuting regression 1008.

For future reference debugging was helped with CFG_VERSAL_TRACE_MBOX.

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Comment by nathan-menhorn** [comment]
Running just an encrypted update on 6680 causes no issues. Additionally, I ran the 10x 8k encrypt updates followed by the 6680 encrypt update using client/server mode to replicate the issue you showed but I couldn't recreate your issue as no timeout was seen:

`[0.015]****************************************
[0.070]Xilinx Versal Platform Loader and Manager
[0.126]Release 2022.1   Jun 17 2022  -  16:33:28
[0.183]Platform Version: v2.0 PMC: v2.0, PS: v2.0
[0.247]BOOTMODE: 0x0, MULTIBOOT: 0x0
[0.298]****************************************
[0.527]Non Secure Boot
[3.405]PLM Initialization Time
[3.453]***********Boot PDI Load: Started***********
[3.511]Loading PDI from SBI
[3.558]Monolithic/Master Device
[3.648]0.113 ms: PDI initialization time
[3.704]+++Loading Image#: 0x1, Name: lpd, Id: 0x04210002
[3.770]---Loading Partition#: 0x1, Id: 0xC
[54.717] 50.862 ms for Partition#: 0x1, Size: 2960 Bytes
[59.571]---Loading Partition#: 0x2, Id: 0xB
[63.947] 0.516 ms for Partition#: 0x2, Size: 48 Bytes
[68.094]---Loading Partition#: 0x3, Id: 0xB
[285.159] 213.203 ms for Partition#: 0x3, Size: 59376 Bytes
[287.566]---Loading Partition#: 0x4, Id: 0xB
[291.518] 0.008 ms for Partition#: 0x4, Size: 1936 Bytes
[296.431]---Loading Partition#: 0x5, Id: 0xB
[300.387] 0.011 ms for Partition#: 0x5, Size: 3536 Bytes
[305.474]+++Loading Image#: 0x2, Name: pl_cfi, Id: 0x18700000
[310.665]---Loading Partition#: 0x6, Id: 0x3
[3274.467] 2959.852 ms for Partition#: 0x6, Size: 707232 Bytes
[3277.133]---Loading Partition#: 0x7, Id: 0x5
[4812.296] 1531.128 ms for Partition#: 0x7, Size: 564304 Bytes
[4814.996]+++Loading Image#: 0x3, Name: fpd, Id: 0x0420C003
[4820.168]---Loading Partition#: 0x8, Id: 0x8
[4824.606] 0.405 ms for Partition#: 0x8, Size: 1536 Bytes
[4829.264]***********Boot PDI Load: Done***********
[4833.760]7139.373 ms: ROM Time
[4836.546]Total PLM Boot Time
 Aes encrypt update 0 for 8192 pass!
 Aes encrypt update 1 for 8192 pass!
 Aes encrypt update 2 for 8192 pass!
 Aes encrypt update 3 for 8192 pass!
 Aes encrypt update 4 for 8192 pass!
 Aes encrypt update 5 for 8192 pass!
 Aes encrypt update 6 for 8192 pass!
 Aes encrypt update 7 for 8192 pass!
 Aes encrypt update 8 for 8192 pass!
 Aes encrypt update 9 for 8192 pass!
 Aes encrypt update for 6680 pass!

GCM tag:
D58F8E2DC2D192E9FC054B6BE90491E8

Successfully ran Versal AES example`


As an additional test, to force a failure in the PLM to make sure the server side was operating as expected IsLast was set to TRUE after sending the first 8k and then sending another 8k of data.

` Aes encrypt update 0 for 8k pass!
[28441.ncr]pt update 8k atchailed: 25Error: IPI command failed for Command ID: 0x563
[28448.734]PLM Error Status: 0x25630051`

@ldts I believe the error is somewhere in the op-tee side, possibly the mailbox, as there is no 16 byte hardware limitation on the DMA as confirmed by the above test code as well as confirmed by the HW team.

Here's the modified client/server example:

`/******************************************************************************
* Copyright (c) 2019 - 2022 Xilinx, Inc. All rights reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/


/*****************************************************************************/
/**
*
* @file	xilsecure_versal_aes_client_example.c
* @addtogroup xsecure_versal_aes_example XilSecure AES API Example Generic Usage
* @{
*
* @note
* This example illustrates the usage of Versal AES APIs, by encrypting the data
* with provided key and IV and decrypt's the output of encrypted data and
* compares with original data and checks for GCM tag match.
*
* To build this application, xilmailbox library must be included in BSP and xilsecure
* must be in client mode
*
* Procedure to link and compile the example for the default ddr less designs
* ------------------------------------------------------------------------------------------------------------
* The default linker settings places a software stack, heap and data in DDR memory. For this example to work,
* any data shared between client running on A72/R5/PL and server running on PMC, should be placed in area
* which is acccessible to both client and server.
*
* Following is the procedure to compile the example on OCM or any memory region which can be accessed by server
*
*		1. Open example linker script(lscript.ld) in Vitis project and section to memory mapping should
*			be updated to point all the required sections to shared memory(OCM or TCM)
*			using a memory region drop down selection
*
*						OR
*
*		1. In linker script(lscript.ld) user can add new memory section in source tab as shown below
*			.sharedmemory : {
*   			. = ALIGN(4);
*   			__sharedmemory_start = .;
*   			*(.sharedmemory)
*   			*(.sharedmemory.*)
*   			*(.gnu.linkonce.d.*)
*   			__sharedmemory_end = .;
* 			} > versal_cips_0_pspmc_0_psv_ocm_ram_0_psv_ocm_ram_0
*
* 		2. Data elements that are passed by reference to the server side should be stored in the above shared
* 			memory section.
*
* To keep things simple, by default the cache is disabled for this example
*
* MODIFICATION HISTORY:
* <pre>
* Ver   Who    Date     Changes
* ----- ------ -------- -------------------------------------------------
* 4.1   vns    08/06/19 First Release
* 4.3   har    10/12/20 Addressed security review comments
* 4.5   har    03/02/21 Added support for AAD
* 	kal    03/23/21 Updated example for client support
*       har    06/02/21 Fixed GCC warnings for R5 compiler
* 4.7   kpt    01/13/22 Added support for PL microblaze
*       kpt    03/16/22 Removed IPI related code and added mailbox support
*
* </pre>
******************************************************************************/

/***************************** Include Files *********************************/
#include "xil_cache.h"
#include "xil_util.h"
#include "xsecure_aesclient.h"
#include "sleep.h"

/************************** Constant Definitions *****************************/

/* Hardcoded KUP key for encryption of data */
#define	XSECURE_AES_KEY	\
	"F878B838D8589818E868A828C8488808F070B030D0509010E060A020C0408000"

/* Hardcoded IV for encryption of data */
#define	XSECURE_IV	"D2450E07EA5DE0426C0FA133"

#define XSECURE_DATA	\
	"1234567808F070B030D0509010E060A020C0408000A5DE08D85898A5A5FEDCA10134" \
	"ABCDEF12345678900987654321123487654124456679874309713627463801AD1056"

#define XSECURE_AAD			"67e21cf3cb29e0dcbc4d8b1d0cc5334b"

#define NUM_OF_8K_DATA (10u)
#define DATA_BYTES_8K (8192u)
#define DATA_BYTES_6K (6680u)

#define XSECURE_DATA_SIZE		(NUM_OF_8K_DATA*DATA_BYTES_8K + DATA_BYTES_6K)
#define XSECURE_DATA_SIZE_IN_BITS	(XSECURE_DATA_SIZE * 8U)
#define XSECURE_IV_SIZE			(12)
#define XSECURE_IV_SIZE_IN_BITS		(XSECURE_IV_SIZE * 8U)
#define XSECURE_KEY_SIZE		(32)
#define XSECURE_KEY_SIZE_IN_BITS	(XSECURE_KEY_SIZE * 8U)
#define XSECURE_AAD_SIZE		(16)
#define XSECURE_AAD_SIZE_IN_BITS	(XSECURE_AAD_SIZE * 8U)

#define XSECURE_PMCDMA_DEVICEID	PMCDMA_0_DEVICE_ID
#define XSECURE_SECURE_GCM_TAG_SIZE	(16U)
#define XSECURE_AES_KEY_SIZE_256 	(2U)
#define XSECURE_SHARED_TOTAL_MEM_SIZE		(XSECURE_SHARED_MEM_SIZE +\
						XSECURE_IV_SIZE + XSECURE_KEY_SIZE)



/**************************** Type Definitions *******************************/

/***************** Macros (Inline Functions) Definitions *********************/

/************************** Function Prototypes ******************************/

static s32 SecureAesExample(XSecure_ClientInstance *InstancePtr, u8* Key, u8* Iv);

/************************** Variable Definitions *****************************/

/* shared memory allocation */
static u8 SharedMem[XSECURE_SHARED_TOTAL_MEM_SIZE] __attribute__((aligned(64U)))
						__attribute__ ((section (".data.SharedMem")));

#if defined (__GNUC__)
static u8 Data[XSECURE_DATA_SIZE]__attribute__ ((aligned (64)))
				__attribute__ ((section (".data.Data")));
static u8 DecData[XSECURE_DATA_SIZE]__attribute__ ((aligned (64)))
				__attribute__ ((section (".data.DecData")));
static u8 EncData[XSECURE_DATA_SIZE]__attribute__ ((aligned (64)))
				__attribute__ ((section (".data.EncData")));
static u8 GcmTag[XSECURE_SECURE_GCM_TAG_SIZE]__attribute__ ((aligned (64)))
				__attribute__ ((section (".data.GcmTag")));
static u8 Aad[XSECURE_AAD_SIZE]__attribute__ ((aligned (64)))
				__attribute__ ((section (".data.Aad")));
#elif defined (__ICCARM__)
#pragma data_alignment = 64
static u8 Data[XSECURE_DATA_SIZE];
#pragma data_alignment = 64
static u8 DecData[XSECURE_DATA_SIZE];
#pragma data_alignment = 64
static u8 EncData[XSECURE_DATA_SIZE ];
#pragma data_alignment = 64
static u8 GcmTag[XSECURE_SECURE_GCM_TAG_SIZE];
#pragma data_alignment = 64
static u8 Aad[XSECURE_AAD_SIZE];
#endif

/************************** Function Definitions ******************************/



/*****************************************************************************/
/**
*
* Main function to call the SecureAesExample function
*
* @param	None
*
* @return
*		- XST_FAILURE if the Aes failed.
*
******************************************************************************/
int main(void)
{
	int Status = XST_FAILURE;
	XMailbox MailboxInstance;
	XSecure_ClientInstance SecureClientInstance;
	u8 *Key = NULL;
	u8 *Iv = NULL;

	#ifdef XSECURE_CACHE_DISABLE
		Xil_DCacheDisable();
	#endif

	Status = XMailbox_Initialize(&MailboxInstance, 0U);
	if (Status != XST_SUCCESS) {
		xil_printf("Mailbox initialize failed:%08x \r\n", Status);
		goto END;
	}

	Status = XSecure_ClientInit(&SecureClientInstance, &MailboxInstance);
	if (Status != XST_SUCCESS) {
		goto END;
	}

	/* Set shared memory */
	Status = XMailbox_SetSharedMem(&MailboxInstance, (u64)(UINTPTR)(SharedMem +
			XSECURE_KEY_SIZE + XSECURE_IV_SIZE), XSECURE_SHARED_MEM_SIZE);
	if (Status != XST_SUCCESS) {
		xil_printf("\r\n Shared Memory initialization failed");
		goto END;
	}


	Key = &SharedMem[0U];
	Iv = (Key + XSECURE_KEY_SIZE);

   /* We don't care about the actual data but simply the size for this test. */
//	/* Covert strings to buffers */
//	Status = Xil_ConvertStringToHexBE((const char *) (XSECURE_AES_KEY),
//			Key, XSECURE_KEY_SIZE_IN_BITS);
//	if (Status != XST_SUCCESS) {
//		xil_printf(
//			"String Conversion error (KEY):%08x !!!\r\n", Status);
//		goto END;
//	}
//
//	Status = Xil_ConvertStringToHexBE( (const char *) (XSECURE_IV),
//			Iv, XSECURE_IV_SIZE_IN_BITS);
//	if (Status != XST_SUCCESS) {
//		xil_printf(
//			"String Conversion error (IV):%08x !!!\r\n", Status);
//		goto END;
//	}
//
//	Status = Xil_ConvertStringToHexBE((const char *) (XSECURE_DATA),
//				Data, XSECURE_DATA_SIZE_IN_BITS);
//	if (Status != XST_SUCCESS) {
//		xil_printf(
//			"String Conversion error (Data):%08x !!!\r\n", Status);
//		goto END;
//	}
//
//	Status = Xil_ConvertStringToHexBE((const char *) (XSECURE_AAD), Aad,
//		XSECURE_AAD_SIZE_IN_BITS);
//	if (Status != XST_SUCCESS) {
//		xil_printf("String Conversion error (AAD):%08x !!!\r\n", Status);
//		goto END;
//	}

	Xil_DCacheFlushRange((UINTPTR)SharedMem, XSECURE_IV_SIZE + XSECURE_KEY_SIZE);
	Xil_DCacheFlushRange((UINTPTR)Data, XSECURE_DATA_SIZE);
	Xil_DCacheFlushRange((UINTPTR)Aad, XSECURE_AAD_SIZE);

	/* Encryption and decryption of the data */
	Status = SecureAesExample(&SecureClientInstance, Key, Iv);
	if(Status == XST_SUCCESS) {
		xil_printf("\r\nSuccessfully ran Versal AES example\r\n");
	}
	else {
		xil_printf("\r\nVersal AES example failed\r\n");
	}

END:
	Status |= XMailbox_ReleaseSharedMem(&MailboxInstance);
	return Status;
}

/****************************************************************************/
/**
*
* This function encrypts the data with provided AES key and IV and decrypts
* the encrypted data also checks whether GCM tag is matched or not and finally
* compares the decrypted data with the original data provided.
*
* @param	InstancePtr Pointter to the client instance
* @param	Key Pointer to AES key
* @param	Iv  Pointer to initialization vector
*
* @return
*		- XST_FAILURE if the Aes example was failed.
*		- XST_SUCCESS if the Aes example was successful
*
* @note		None.
*
****************************************************************************/
/** //! [Generic AES example] */
static s32 SecureAesExample(XSecure_ClientInstance *InstancePtr, u8 *Key, u8 *Iv)
{
	s32 Status = XST_FAILURE;
	u32 Index;

	/* Initialize the Aes driver so that it's ready to use */
	Status = XSecure_AesInitialize(InstancePtr);

	if (Status != XST_SUCCESS) {
		xil_printf(" Aes encrypt init is failed\n\r");
		goto END;
	}

	/* Write AES key */
	Status = XSecure_AesWriteKey(InstancePtr, XSECURE_AES_USER_KEY_0,
				XSECURE_AES_KEY_SIZE_256, (UINTPTR)Key);
	if (Status != XST_SUCCESS) {
		xil_printf("Failure at key write\n\r");
		goto END;
	}

	Xil_DCacheInvalidateRange((UINTPTR)EncData, XSECURE_DATA_SIZE);
	Xil_DCacheInvalidateRange((UINTPTR)GcmTag, XSECURE_SECURE_GCM_TAG_SIZE);

	Status = XSecure_AesEncryptInit(InstancePtr, XSECURE_AES_USER_KEY_0,
			XSECURE_AES_KEY_SIZE_256, (UINTPTR)Iv);

	if (Status != XST_SUCCESS) {
		xil_printf(" Aes encrypt init is failed\n\r");
		goto END;
	}

	Status = XSecure_AesUpdateAad(InstancePtr, (UINTPTR)Aad, XSECURE_AAD_SIZE);
	if (Status != XST_SUCCESS) {
		xil_printf(" Aes update aad failed %x\n\r", Status);
		goto END;
	}


   for (uint8_t i = 0u; i < NUM_OF_8K_DATA; i++) 
   {
      Status = XSecure_AesEncryptUpdate(InstancePtr, (UINTPTR)&Data,(UINTPTR)EncData,
            DATA_BYTES_8K, FALSE);
      if (Status != XST_SUCCESS) {
         xil_printf(" Aes encrypt update 8k is failed: %08X\n\r", Status);
         goto END;
      }
      else {
         xil_printf(" Aes encrypt update %d for 8192 pass!\r\n", i);
      }
   }

	Status = XSecure_AesEncryptUpdate(InstancePtr, (UINTPTR)&Data,(UINTPTR)EncData,
						DATA_BYTES_6K, TRUE);
	if (Status != XST_SUCCESS) {
		xil_printf(" Aes encrypt update 6k is failed:%08X\n\r", Status);
		goto END;
	}
   else {
      xil_printf(" Aes encrypt update for 6680 pass!\r\n", DATA_BYTES_6K);
   }

 	Status = XSecure_AesEncryptFinal(InstancePtr, (UINTPTR)&GcmTag);
 	if (Status != XST_SUCCESS) {
 		xil_printf("Failed at GCM tag generation\n\r");
 		goto END;
 	}
 
 	Xil_DCacheInvalidateRange((UINTPTR)EncData, XSECURE_DATA_SIZE);
	Xil_DCacheInvalidateRange((UINTPTR)GcmTag, XSECURE_SECURE_GCM_TAG_SIZE);

	xil_printf("GCM tag: \n\r");
	for (Index = 0; Index < XSECURE_SECURE_GCM_TAG_SIZE; Index++) {
		xil_printf("%02x", GcmTag[Index]);
	}
	xil_printf( "\r\n\n");

END:
	return Status;
}
/** //! [Generic AES example] */
/** @} */
`

**Comment by ldts** [comment]
I'll have a look again but it does seem a problem in the PLM: a DMA timeout - the only one I know- is typically because the engine cant address the memory and the 'work around' is only to add a few extra zeros so the length matches a different more generic alignment.

I am not sure yet how this can be an OP-TEE problem: on every call the buffer address is valid and only the length causes the PLM to program the DMA in a way that it ends up timing out. 

This is a use case that regardless MUST have an additional PLM check to trap the condition that leads to the DMA going south so yes, it is worth that we understand the use case a bit better. will look into it.

**Comment by ldts** [comment]
@nathan-menhorn also notice that this work around doesnt impose any requirements on alignment: since the size of the buffer mapped to the PLM is large enough is just a matter of passing some extra zeros on the buffer already mapped.

But I agree, we need to find out what is going on since you cant reproduce with your sample code.

**Comment by nathan-menhorn** [comment]
Hi @ldts,
Have you tested the image that was sent on Slack? Can you send me the log (either through here, Slack, or email)? Thanks.

**Pull request merged**
