### PR TITLE
imx7ulp: fix shutdown

### PR DESCRIPTION
**Pull request by vanmaegima**
Missed patches during the 3.10 -> 3.15 migration.
After approved, I will work on a PR for 3.17 as well.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
I don't think we need imx_caam anymore, as that was replaced with https://github.com/OP-TEE/optee_os/pull/3608. In theory CFG_NXP_CAAM_BLOB_DRV is already enabled, but I wonder if things are still missing for imx7ulp here.

I would prefer to add what is missing to the current driver (in 3.15 and 3.17) instead of adding back these changes (the imx7ulp stuff seems ok).

**Comment by ricardosalveti** [comment]
```
else ifneq (,$(filter $(PLATFORM_FLAVOR),$(mx7ulp-flavorlist)))
$(call force,CFG_MX7ULP,y)
$(call force,CFG_TEE_CORE_NB_CORE,1)
$(call force,CFG_TZC380,n)
$(call force,CFG_CSU,n)
$(call force,CFG_NXP_CAAM,y)
$(call force,CFG_IMX_CAAM,n)
```

In theory NXP_CAAM is already available for 7ulp.

**Comment by vanmaegima** [comment]
@ricardosalveti I was unsure if I could drop these patches because of the HUK, let me test shutdown without them.

**Comment by vanmaegima** [comment]
@ricardosalveti confirmed that the 2 patches are enough for this purpose.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
