### PR TITLE
[FIO toup] drivers: imx_i2c: add support for MX8MP

### PR DESCRIPTION
**Pull request by vanmaegima**
Add I2C driver support for iMX8MP.

Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
LGTM, please also send this one upstream, should land without issues.

**Comment by vanmaegima** [comment]
@ricardosalveti I just noticed that the SCL/SDA offsets vary and 8MP supports two additional buses. I will take more time to work on this one.

**Review by ricardosalveti — APPROVED** [review]
LGTM, please send the same patch upstream.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Pull request merged**
