### PR TITLE
3.18+fio.se050f

### PR DESCRIPTION
**Pull request by ldts**

### CODE REVIEW

**Comment by ldts** [comment]
https://github.com/OP-TEE/optee_os/pull/5610

**Comment by ldts** [comment]
@ricardosalveti updated

**Comment by ricardosalveti** [comment]
@ldts since upstream should be merged at any moment now (based on the reviews), mind doing a cherry-pick from the 3 patches proposed there? Easier to match later when doing a rebase. Thanks!

**Comment by ldts** [comment]
@ricardosalveti updated

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
