### PR TITLE
3.20+fio

### PR DESCRIPTION
**Pull request by igoropaniuk**
Tested on stm32mp15-disco

```
+-----------------------------------------------------
30129 subtests of which 0 failed
128 test cases of which 0 failed
0 test cases were skipped
TEE test application done!

```

### CODE REVIEW

**Comment by MrCry0** [comment]
this fixes building imx6ul: https://github.com/MrCry0/optee_os/commit/587097957eb2e7f11990fb130a76416da76f5539

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
I think we can drop the current 7ulp support as that is not really tested properly, and we're also going to leverage the NXP fork instead for it, until we know what might be missing or broken (since they have a lot more relevant changes for it that are critical for us).

So patches we can drop:
- [FIO toup] imx7ulp: CFG_IMX_LPUART selectable
- [FIO toup] imx: make CONSOLE_UART_BASE optional
- [FIO toup] imx7ulp: add definition for SNVS_BASE
- [FIO toup] plat-imx: enable NXP_CAAM on imx7ulp
- [FIO internal] core: imx: add mx7ulpeaucom platform flavor
- [FIO fromtree] MLK-19654 Reduce size allocated to OCRAM suspend code
- [FIO internal] core: mach-imx: pick needed definitions for 7ulp from NXP
- [FIO toup] imx7ulp: psci: cpu_suspend support
- [FIO toup] imx7ulp: drivers: watchdog: fix timing issue

**Comment by igoropaniuk** [comment]
@ricardosalveti done

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
