### PR TITLE
[FIO internal]: : se050: scp03: prohibit derived keys without RPMB ready

### PR DESCRIPTION
**Pull request by ldts**
Prevents SCP03 rotation from using the derived keys unless RPMB is available.

This commit must be used particularly when
CFG_CORE_SE05X_SCP03_PROVISION_ON_INIT has been enabled.

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by ldts** [comment]
@mike-scott this is needed to use CFG_CORE_SE05X_SCP03_PROVISION_ON_INIT safely.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by mike-scott — APPROVED** [review]

**Comment by ricardosalveti** [comment]
@ldts can you define a better patch subject for this one?

**Comment by ldts** [comment]
> @ldts can you define a better patch subject for this one?

better in what sense.  This subject was intentionally unusual...forgetting this patch will cause customer products to break.
if you want a subject proper/upstream-able/subtel I can certainly do it but are you sure we should?

**Comment by ricardosalveti** [comment]
> better in what sense. This subject was intentionally unusual...forgetting this patch will cause customer products to break.
> if you want a subject proper/upstream-able/subtel I can certainly do it but are you sure we should?

One that explains what it is doing from the subject line pov :-) Otherwise git log won't necessarily make sense from the functionality point of view.

It is fine to explain as part of the body message why this one is critical, we always review patches as we do rebases.

**Comment by ricardosalveti** [comment]
One example, git shortlog will just show DO NOT DROP when we bump the rev in meta-lmp, which means nothing.

**Comment by ldts** [comment]
oops, forgot about this. ok doing it now.

**Comment by ldts** [comment]
@ricardosalveti will you pick it up or shall I rebase and merge?

**Comment by MrCry0** [comment]
+1

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
