### PR TITLE
[FIO internal] imx7ulp: psci: cpu_suspend support

### PR DESCRIPTION
**Pull request by vanmaegima**
This commit provides support for suspend

Test:
$ echo mem > /sys/power/state OR
$ echo standby > /sys/power/state

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
(cherry picked from commit 837e67b82ec614f2e94aa6b480c14643de71f59d)
(cherry picked changes from NXP commit c013478890dbfe3fbe6cfe485020a0d9ea8ea34d)
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM does it go to the correct power state?

**Comment by vanmaegima** [comment]
@Tim-Anderson yes, suspends directly to VLLS, reboot works fine too.

**Review by mike-scott — APPROVED** [review]
Nice.  Much cleaner.  LGTM

**Pull request merged**
