### PR TITLE
3.18+fio+se050 fallback

### PR DESCRIPTION
**Pull request by ldts**

### CODE REVIEW

**Comment by ldts** [comment]
https://github.com/OP-TEE/optee_os/pull/5696

**Comment by ldts** [comment]
By default CFG_NXP_SE05X_RSA_DRV_FALLBACK is disabled.

This means that a lot of xtests will fail on the SE050-F (rsa <2048, ecc < 224, ECDH, RSA_NOPAD...)

Since the SE050-F doesnt implement that functionality for a reason (FIPS certification), I'd suggest that we keep the fallback disabled except for regression testing with xtests.

**Comment by ldts** [comment]
xtested on imx8mm with 0xA92A and 0xA1F4 devices

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
