### PR TITLE
SM SYSTEM_RESET2 support

### PR DESCRIPTION
**Pull request by igoropaniuk**

### CODE REVIEW

**Comment by igoropaniuk** [comment]
We should try to upstream that

I'll also double check if I haven't missed any changes between PSCI spec v 0.2 vs 1.1 if we decide to upstream that

**Comment by ricardosalveti** [comment]
Agree we should also try to upstream this one. Mind changing the commit tag to toup instead of internal? And feel free to start the discussion with upstream in parallel.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Pull request merged**
