### PR TITLE
imx7ulp: fix suspending to vlls instead of vlps

### PR DESCRIPTION
**Pull request by vanmaegima**
Add calls to power management framework. This framework only applies to
ARMv7 SoC.

Signed-off-by: Silvano di Ninno <silvano.dininno@nxp.com>
(cherry picked from commit a8677a18c4bd6ff4728e842b53e92d69b1fa962c)
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

### CODE REVIEW

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by mike-scott — APPROVED** [review]
Nice pull from upstream.  LGTM.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
